### PR TITLE
More ideas

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by coomlata1** [comment]
Hi...
I submitted another copy of the script after you had submitted your pull, so the file was out of sync.  Rather than use the command line to do a manual merge, I made the changes you suggested and loaded a new copy in the editor.  All is well...Thank you.  Excellent coding.  I'm learning the benefits of good string formatting techniques.  One of the reasons I don't leave spaces between equal signs and variables is because I'm coding on an iPhone and I am trying to conserve as much space as possible.  Probably not a good habit to get into.  Your way is much easier to read.

**Comment by cclauss** [comment]
I pushed 4 different commits into this one pull request...  Sorry about that.  Usually I bundle them all up into one commit.  Please check the last commit.

**Comment by cclauss** [comment]
In the end, `get_weather_dicts()` should look like this:

``` python
def get_weather_dicts(lat,lon,city,id):
        url_fmt = 'http://api.openweathermap.org/data/2.5/{}?{}'
        if city: # From entered city
                fmt = 'q={}&type=accurate&units={}'
                query = fmt.format(city, imperial_or_metric)
        elif id: # From list
                fmt = 'id={}&type=accurate&units={}'
                query = fmt.format(id, imperial_or_metric)
        else: # From where you are now
                fmt = 'lat={}&lon={}&type=accurate&units={}'
                query = fmt.format(lat, lon, imperial_or_metric)
        w_url = url_fmt.format('weather', query)
        f_url = url_fmt.format('forecast/daily', query) + '&cnt={}'.format(day_count)
        try:
                weather = requests.get(w_url).json()
                forecast = requests.get(f_url).json()
                #import pprint;pprint.pprint(weather)
                #import pprint;pprint.pprint(forecast)
                #See: http://bugs.openweathermap.org/projects/api/wiki
                #sys.exit()
        except requests.ConnectionError:
                print('=' * 20) # console.clear()
                sys.exit('Weather servers are busy. Try again in a few minutes...')
        return weather, forecast
```

**Comment by cclauss** [comment]
I will put this in a NEW pull request and close this one.

**Pull request closed without merging**
