### PR TITLE
Print as a function to get ready for Python3

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by coomlata1** [comment]
Thank you again...This was the first script I wrote in Python and naming conventions show my inconsistencies.  Thanks too for the update on the print function.

**Comment by cclauss** [comment]
I was hacking with a free Python editor called PyCharm 4.0 Community Edition and it suggests fixes for all kinda things so that is where this round of changes came from.

**Comment by coomlata1** [comment]
Just downloaded that editor and am taking a look at it.  Loaded up the
weather app and it is suggesting quite a few changes but I hesitate to do
too much as I still need to familarize myself with what is critical and
what isn't and how it will effect the behaviour in Pythonista vs Python.

**Comment by cclauss** [comment]
Yes.  It will claim that it can't import the scene module, etc. but that is not a problem.  Much of what it complains about is just noise that can safely be ignored.  There was a great video from PyCon last week on the problems that arise from too much focus on PEP8: http://www.youtube.com/watch?v=wf-BqAjZb8M

**Pull request merged**
